before:
  hooks:
    - go mod download
builds:
  - id: darkroom_linux
    main: .
    goos:
      - linux
    goarch:
      - amd64
      - 386
    env:
      - CGO_ENABLED=1
    ldflags:
      - -w -s
      - -X github.com/gojek/darkroom/internal/version.version={{ .Version }}
      - -X github.com/gojek/darkroom/internal/version.gitTag={{ .Tag }}
      - -X github.com/gojek/darkroom/internal/version.gitCommit={{ .FullCommit }}
      - -X github.com/gojek/darkroom/internal/version.buildDate={{ .Date }}
  - id: darkroom_windows_32bit
    main: .
    goos:
      - windows
    goarch:
      - 386
    ldflags:
      - -w -s
      - -X github.com/gojek/darkroom/internal/version.version={{ .Version }}
      - -X github.com/gojek/darkroom/internal/version.gitTag={{ .Tag }}
      - -X github.com/gojek/darkroom/internal/version.gitCommit={{ .FullCommit }}
      - -X github.com/gojek/darkroom/internal/version.buildDate={{ .Date }}
    env:
      - CGO_ENABLED=1
      - CC=i686-w64-mingw32-gcc
      - CXX=i686-w64-mingw32-g++
  - id: darkroom_windows_64bit
    main: .
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -w -s
      - -X github.com/gojek/darkroom/internal/version.version={{ .Version }}
      - -X github.com/gojek/darkroom/internal/version.gitTag={{ .Tag }}
      - -X github.com/gojek/darkroom/internal/version.gitCommit={{ .FullCommit }}
      - -X github.com/gojek/darkroom/internal/version.buildDate={{ .Date }}
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
  - id: darkroom_darwin
    main: .
    goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - -w -s
      - -X github.com/gojek/darkroom/internal/version.version={{ .Version }}
      - -X github.com/gojek/darkroom/internal/version.gitTag={{ .Tag }}
      - -X github.com/gojek/darkroom/internal/version.gitCommit={{ .FullCommit }}
      - -X github.com/gojek/darkroom/internal/version.buildDate={{ .Date }}
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
dockers:
  - dockerfile: build/Dockerfile.goreleaser
    goos: linux
    goarch: amd64
    image_templates:
      - "gojektech/darkroom:latest"
      - "gojektech/darkroom:{{ .Tag }}"
env:
  - CGO_ENABLED=1
  - GO111MODULE=on
archives:
  - replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      386: 32-bit
      amd64: 64-bit
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^website"
