before:
  hooks:
  - go mod download
builds:
- id: darkroom_linux
  main: .
  goos:
  - linux
  goarch:
  - amd64
  env:
  - CGO_ENABLED=1
  ldflags:
  - -w -s
  - -X github.com/gojek/darkroom/internal/version.version={{ .Version }}
  - -X github.com/gojek/darkroom/internal/version.gitTag={{ .Tag }}
  - -X github.com/gojek/darkroom/internal/version.gitCommit={{ .FullCommit }}
  - -X github.com/gojek/darkroom/internal/version.buildDate={{ .Date }}
- id: darkroom_windows
  main: .
  goos:
  - windows
  goarch:
  - amd64
  ldflags:
  - -w -s
  - -X github.com/gojek/darkroom/internal/version.version={{ .Version }}
  - -X github.com/gojek/darkroom/internal/version.gitTag={{ .Tag }}
  - -X github.com/gojek/darkroom/internal/version.gitCommit={{ .FullCommit }}
  - -X github.com/gojek/darkroom/internal/version.buildDate={{ .Date }}
  env:
  - CGO_ENABLED=1
  - CC=x86_64-w64-mingw32-gcc
  - CXX=x86_64-w64-mingw32-g++
- id: darkroom_darwin
  main: .
  goos:
  - darwin
  goarch:
  - amd64
  - arm64
  ldflags:
  - -w -s
  - -X github.com/gojek/darkroom/internal/version.version={{ .Version }}
  - -X github.com/gojek/darkroom/internal/version.gitTag={{ .Tag }}
  - -X github.com/gojek/darkroom/internal/version.gitCommit={{ .FullCommit }}
  - -X github.com/gojek/darkroom/internal/version.buildDate={{ .Date }}
  env:
  - CGO_ENABLED=1
  - CC=o64-clang
  - CXX=o64-clang++
dockers:
- dockerfile: build/Dockerfile.goreleaser
  goos: linux
  goarch: amd64
  image_templates:
  - "gojektech/darkroom:latest"
  - "gojektech/darkroom:{{ .Tag }}"

archives:
- format: tar.gz
  name_template: >-
    {{ .ProjectName }}_
    {{- title .Os }}_
    {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "386" }}i386
    {{- else }}{{ .Arch }}{{ end }}
    {{- if .Arm }}v{{ .Arm }}{{ end }}
  format_overrides:
  - goos: windows
    format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"
    - "^website"
