{
 "title": "Darkroom",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Resize Processing Stats(95th %ile)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(image_process_duration_bucket{process=\"resizeDuration\"}[5m]))",
     "legendFormat": "{{image_type}}"
    }
   ]
  },
  {
   "title": "Crop Processing Stats (95th %ile)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(image_process_duration_bucket{process=\"cropDuration\"}[5m]))",
     "legendFormat": "{{image_type}}"
    }
   ]
  },
  {
   "title": "Grayscale Processing Stats (95th %ile)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(image_process_duration_bucket{process=\"grayScaleDuration\"}[5m]))",
     "legendFormat": "{{image_type}}"
    }
   ]
  },
  {
   "title": "Encode Processing Stats (95th %ile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(image_process_duration_bucket{process=\"encodeDuration\"}[5m]))",
     "legendFormat": "{{image_type}}"
    }
   ]
  },
  {
   "title": "Decode Processing Stats (95th %ile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(image_process_duration_bucket{process=\"decodeDuration\"}[5m]))",
     "legendFormat": "{{image_type}}"
    }
   ]
  },
  {
   "title": "Scale Processing Stats (95th %ile)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(image_process_duration_bucket{process=\"scaleDuration\"}[5m]))",
     "legendFormat": "{{image_type}}"
    }
   ]
  },
  {
   "title": "Rotate Processing Stats (95th %ile)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(image_process_duration_bucket{process=\"rotateDuration\"}[5m]))",
     "legendFormat": "{{image_type}}"
    }
   ]
  },
  {
   "title": "Flip Processing Stats (95th %ile)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(image_process_duration_bucket{process=\"flipDuration\"}[5m]))",
     "legendFormat": "{{image_type}}"
    }
   ]
  },
  {
   "title": "Fix Orientation Processing Stats (95th %ile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(image_process_duration_bucket{process=\"fixOrientation\"}[5m]))",
     "legendFormat": "{{image_type}}"
    }
   ]
  },
  {
   "title": "Blur Processing Stats (95th %ile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(image_process_duration_bucket{process=\"blurDuration\"}[5m]))",
     "legendFormat": "{{image_type}}"
    }
   ]
  },
  {
   "title": "Average Rate of Storage Get Errors(ImageHandler)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(image_handler_errors{error_type=\"handler.storage.get.error\"}[5m]))"
    }
   ]
  },
  {
   "title": "Average Rate of Processor Errors(Image Handler)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(image_handler_errors{error_type=\"handler.processor.error\"}[5m]))"
    }
   ]
  }
 ]
}