name: Release

on:
  push:
    branches: [ master ]
    tags:
      - v\d+.\d+.\d+

jobs:
  release:
    name: Docker Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Push
        run: |
          docker run --rm --privileged -v $(pwd):/darkroom \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v $(which docker):$(which docker) -w /darkroom \
          ajatprabha/ci-goreleaser \
          /bin/bash -c "echo ${{ secrets.DOCKER_PASSWORD }} | docker login docker.io --username ${{ secrets.DOCKER_USERNAME }} --password-stdin && GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} goreleaser release --skip-validate --rm-dist"
  release-docs:
    name: Publish GH Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Add key to allow access to repository
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.GH_PAGES_DEPLOY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat <<EOT >> ~/.ssh/config
          Host github.com
          HostName github.com
          IdentityFile ~/.ssh/id_rsa
          EOT
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
        run: |
          cd website
          git config --global user.email "actions@gihub.com"
          git config --global user.name "gh-actions"
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npx docusaurus deploy
